[package]
name = "flatstream-hfuzz"
version = "0.1.0"
edition = "2021"
publish = false

[dependencies]
honggfuzz = "0.5"
flatstream = { path = "../.." }

[[bin]]
name = "deframe_hfuzz"
path = "src/deframe_hfuzz.rs"

